extends SceneTree
## M2 balance runner (task 022, D-126). Headless: plays every strategy x seed of run_m2
## through SimWorld.step() (no SimDriver, no scene) and writes a Markdown report.
## godot --headless --path game -s res://balance/balance_runner.gd -- --runs N --out <path> [--commit C]
## Exit code 0 even when the targets are missed (the report says so).

const RUN_ID: String = "run_m2"
const STRATEGIES: PackedStringArray = ["passive", "spread", "ring"]
## A run still alive at MAX_SEC is a timeout (not won). The final boss spawns at 900 s.
const MAX_SEC: int = 1000
const MINUTE: int = 60 * SimWorld.TICK_RATE
## Target: the best builder wins at least this share of seeds; passive wins none.
const TARGET_WIN_RATE: float = 0.6


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var runs := 5
	var out := "res://../reports/balance_m2.md"
	var meta := {"date": Time.get_date_string_from_system(), "commit": "?"}
	for i in args.size() - 1:
		match args[i]:
			"--runs": runs = int(args[i + 1])
			"--out": out = args[i + 1]
			"--commit": meta.commit = args[i + 1]
	var results: Array[Dictionary] = []
	var strategies := STRATEGIES
	for i in args.size() - 1:
		if args[i] == "--only":
			strategies = args[i + 1].split(",")
	for strategy in strategies:
		for s in range(1, runs + 1):
			var r := run_one(strategy, s, MAX_SEC)
			print("%s seed %d: %s at %s, %d towers, %.1f s wall" % [strategy, s, r.outcome, _mmss(r.end_sec),
				r.towers_bought, r.wall_ms / 1000.0])
			results.append(r)
	var text := report(results, runs, meta)
	var f := FileAccess.open(out, FileAccess.WRITE)
	if f == null:
		push_error("cannot write " + out)
		quit(1)
		return
	f.store_string(text)
	f.close()
	print(text.substr(0, text.find("## Data")))
	quit(0)


## Plays one run. on_step (optional) is called with the world after every step.
static func run_one(strategy: String, run_seed: int, max_sec: int, on_step: Callable = Callable()) -> Dictionary:
	var t0 := Time.get_ticks_msec()
	var w := SimWorld.new(run_seed)
	var bot := BalanceBot.new(strategy)
	w.queue(SimCommand.start_run(0, run_seed, RUN_ID))
	var r := {"strategy": strategy, "seed": run_seed, "towers_bought": 0, "husks_rebuilt": 0,
		"skills_used": 0, "minutes": []}
	var seen := {}
	var earned := 0
	var max_ticks := max_sec * SimWorld.TICK_RATE
	while w.run_state != SimWorld.RunState.WON and w.run_state != SimWorld.RunState.LOST and w.clock < max_ticks:
		if w.tick % BalanceBot.ACT_TICKS == 0:
			bot.act(w)
		w.step()
		var ev := w.events
		for e in ev.count:
			match ev.kind[e]:
				SimEvents.Kind.ENEMY_DIED:
					earned += int(ev.value[e])
				SimEvents.Kind.SKILL_USED:
					r.skills_used += 1
				SimEvents.Kind.TOWER_PLACED:
					if seen.has(ev.a[e]):
						r.husks_rebuilt += 1
					else:
						seen[ev.a[e]] = true
						r.towers_bought += 1
		if on_step.is_valid():
			on_step.call(w)
		if w.run_state == SimWorld.RunState.RUNNING and w.clock % MINUTE == 0:
			var alive := 0
			for t in w.towers.count():
				alive += 1 - w.towers.husk[t]
			r.minutes.append({"hp": int(w.guardian_hp), "gold": w.gold, "earned": earned, "towers": alive, "enemies": w.enemies.count()})
	r.outcome = {SimWorld.RunState.WON: "won", SimWorld.RunState.LOST: "lost"}.get(w.run_state, "timeout")
	r.end_sec = w.clock / SimWorld.TICK_RATE
	r.earned = earned
	r.hash = w.state_hash()
	r.wall_ms = Time.get_ticks_msec() - t0
	return r


## The Markdown report for `results` (run_one dictionaries), `runs` seeds per strategy.
static func report(results: Array[Dictionary], runs: int, meta: Dictionary = {}) -> String:
	var s := "# Balance M2 (headless bot, task 022, D-126)\n\n"
	s += "Generated by `scripts\\balance.ps1`. Run date %s, commit %s, N = %d seeds per strategy, MAX_SEC = %d. " % [
		meta.get("date", "?"), meta.get("commit", "?"), runs, MAX_SEC]
	s += "Placeholder numbers: the owner reviews at CP-M2 (needs-human:balance).\n\n"
	s += "| Strategy | Wins | Win rate | Death time median (min-max) | Win time | Wall s (total) |\n|---|---|---|---|---|---|\n"
	var wins := {}
	for strategy in STRATEGIES:
		var rs := results.filter(func(r: Dictionary) -> bool: return r.strategy == strategy)
		var deaths: Array = rs.filter(func(r: Dictionary) -> bool: return r.outcome == "lost").map(
			func(r: Dictionary) -> int: return r.end_sec)
		var won: Array = rs.filter(func(r: Dictionary) -> bool: return r.outcome == "won").map(
			func(r: Dictionary) -> String: return _mmss(r.end_sec))
		wins[strategy] = won.size()
		deaths.sort()
		var death := "-" if deaths.is_empty() else "%s (%s-%s)" % [_mmss(deaths[deaths.size() / 2]),
			_mmss(deaths[0]), _mmss(deaths[-1])]
		var wall := 0
		for r: Dictionary in rs:
			wall += r.wall_ms
		s += "| %s | %d / %d | %d %% | %s | %s | %.1f |\n" % [strategy, won.size(), runs,
			roundi(100.0 * won.size() / maxi(runs, 1)), death, ", ".join(won) if won else "-", wall / 1000.0]
	var best := maxi(wins.get("spread", 0), wins.get("ring", 0))
	var met: bool = best >= ceili(TARGET_WIN_RATE * runs) and wins.get("passive", 0) == 0
	s += "\n**Targets** (best of spread / ring wins >= %d %%, passive wins none): **%s**\n" % [
		roundi(TARGET_WIN_RATE * 100), "met" if met else "NOT met"]
	for strategy in STRATEGIES:
		s += "\n## %s\n\n| Seed | Outcome | End | Towers bought | Husks rebuilt | Skills used | Gold earned | Wall s |\n|---|---|---|---|---|---|---|---|\n" % strategy
		var rs := results.filter(func(r: Dictionary) -> bool: return r.strategy == strategy)
		for r: Dictionary in rs:
			s += "| %d | %s | %s | %d | %d | %d | %d | %.1f |\n" % [r.seed, r.outcome, _mmss(r.end_sec),
				r.towers_bought, r.husks_rebuilt, r.skills_used, r.earned, r.wall_ms / 1000.0]
		s += "\nMedian per minute across the runs still alive:\n\n| Min | Runs | Guardian hp | Gold earned | Gold on hand | Towers alive | Live enemies |\n|---|---|---|---|---|---|---|\n"
		var m := 0
		while true:
			var rows := rs.filter(func(r: Dictionary) -> bool: return r.minutes.size() > m).map(
				func(r: Dictionary) -> Dictionary: return r.minutes[m])
			if rows.is_empty():
				break
			s += "| %d | %d | %d | %d | %d | %d | %d |\n" % [m + 1, rows.size(), _median(rows, "hp"), _median(rows, "earned"),
				_median(rows, "gold"), _median(rows, "towers"), _median(rows, "enemies")]
			m += 1
	return s + "\n" + _data()


static func _median(rows: Array, key: String) -> int:
	var v: Array = rows.map(func(r: Dictionary) -> int: return int(r[key]))
	v.sort()
	return v[v.size() / 2]


# Short form for data floats (float32 -> "3.2", not "3.20000004768372").
static func _n(v: float) -> String:
	return str(snappedf(v, 0.01))


static func _mmss(sec: int) -> String:
	return "%d:%02d" % [sec / 60, sec % 60]


# The numbers the runs used, from the data files.
static func _data() -> String:
	var ec := EnemyCatalog.load_dir()
	var tc := TowerCatalog.load_dir()
	var run := RunData.load_id(RUN_ID, ec, tc)
	var tps := float(SimWorld.TICK_RATE)
	var s := "## Data\n\n`%s`: starting gold %d, Guardian hp %d, build radius %.0f, wave %d s + break %d s, " % [
		RUN_ID, run.starting_gold, run.guardian_hp, run.build_radius, run.wave_ticks / tps, run.break_ticks / tps]
	s += "wave counts %s (last repeats).\n\n" % ", ".join(Array(run.wave_count).map(func(c: int) -> String: return str(c)))
	for k in run.skill_ids.size():
		s += "Skill `%s`: cooldown %.0f s, radius %s, damage %s, absorb %s, duration %.0f s.\n" % [run.skill_ids[k],
			run.skill_cooldown[k] / tps, _n(run.skill_radius[k]), _n(run.skill_damage[k]), _n(run.skill_absorb[k]),
			run.skill_duration[k] / tps]
	s += "\n"
	s += "| Tower | Cost | Per copy | Damage | Cooldown s | Range | HP |\n|---|---|---|---|---|---|---|\n"
	for t in tc.ids.size():
		s += "| %s | %d | %d | %s | %.2f | %s | %s |\n" % [tc.ids[t], tc.cost[t], tc.cost_per_copy[t], _n(tc.damage[t]),
			tc.cooldown[t] / tps, _n(tc.attack_range[t]), _n(tc.hp[t])]
	s += "\n| Enemy | HP | Speed | Damage | Gold (chance) | Spawns |\n|---|---|---|---|---|---|\n"
	for e in ec.ids.size():
		var when := ""
		if e == run.final_boss_type:
			when = "final boss %d s" % (run.final_boss_tick / SimWorld.TICK_RATE)
		elif run.boss_types.has(e):
			when = "mini-boss %d s" % (run.boss_ticks[run.boss_types.find(e)] / SimWorld.TICK_RATE)
		s += "| %s | %s | %s | %s | %d (%s) | %s |\n" % [ec.ids[e], _n(ec.hp[e]), _n(ec.speed[e]), _n(ec.damage[e]), ec.gold[e],
			_n(ec.gold_chance[e]), when if when else "waves"]
	return s
